[package]
name = "beancount-exp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
beancount_parser_2 = '1.0.0-alpha.9'
rust_decimal = "*"
