[package]
name = "bean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
beancount_parser_2 = '1.0.0-alpha.11'
clap = { version = "4.3.4", features = ["derive"] }
itertools = "*"
rust_decimal = "*"
